#!/usr/bin/env python3

"""
FILE: 02-add-signature

DESCRIPTION:
    Add signature to commit message

AUTHOR:    Kai Blume, kai.blume@avionic-design.de
COMPANY:   Avionic Design
REVISION:  00
CREATED:   25.01.2024
"""


import sys
import subprocess

"""
Get the value of a git configuration option.
Args:
    key (str): The configuration key to retrieve.
Returns:
    str: The value of the configuration option, or None if not found.
"""


def get_git_config(key):
    try:
        value = (
            subprocess.check_output(["git", "config", "--get", key])
            .strip()
            .decode("utf-8")
        )
        return value
    except subprocess.CalledProcessError:
        return None


"""
Main function to append signature to commit message.
"""


def main():
    commit_msg_file = sys.argv[1]

    user_name = get_git_config("user.name")
    user_email = get_git_config("user.email")

    if user_name and user_email:
        signature = f"\nSigned-off-by: {user_name} <{user_email}>\n"

        with open(commit_msg_file, "a") as f:
            f.write(signature)


if __name__ == "__main__":
    main()
